/**
 * Thin TypeScript wrapper around the WASM Coordinator.
 * Handles camelCase ↔ snake_case conversion at the boundary.
 *
 * WASM is loaded from base64-inlined data (generated by scripts/encode-wasm.mjs)
 * so the final build is a single self-contained HTML file.
 */

import type { AgentConfig, AgentState, AgentStatus, Message } from './types'
import { WASM_BASE64 } from '../wasm/wasm_data'

// Use the generated wasm-pack types
type WasmCoordinator = import('../wasm/gremlin_coordinator').Coordinator

let instance: WasmCoordinator | null = null
let ready = false

export async function initCoordinator(): Promise<void> {
  if (ready) return

  const mod = await import('../wasm/gremlin_coordinator.js')

  if (WASM_BASE64) {
    // Preferred: decode inlined base64 (works from file:// or any origin, no fetch needed)
    const binary = Uint8Array.from(atob(WASM_BASE64), (c) => c.charCodeAt(0))
    await mod.default(binary.buffer)
  } else {
    // Dev fallback: let wasm-bindgen fetch the .wasm file from the dev server
    await mod.default()
  }

  instance = new mod.Coordinator()
  ready = true
}

export function isReady(): boolean {
  return ready
}

function wasm(): WasmCoordinator {
  if (!instance) throw new Error('WASM coordinator not initialised — call initCoordinator() first')
  return instance
}

// ─── Agent management ──────────────────────────────────────────────────────────

export function addAgent(cfg: AgentConfig): void {
  wasm().add_agent(
    JSON.stringify({
      id: cfg.id,
      name: cfg.name,
      role: cfg.role,
      system_prompt: cfg.systemPrompt,
      color: cfg.color,
    }),
  )
}

export function removeAgent(id: string): void {
  wasm().remove_agent(id)
}

interface RawAgentState {
  config: { id: string; name: string; role: string; system_prompt: string; color: string }
  status: string
  message_count: number
  unread_count: number
}

export function getAgents(): AgentState[] {
  const raw: RawAgentState[] = JSON.parse(wasm().get_agents_json())
  return raw.map((a) => ({
    id: a.config.id,
    name: a.config.name,
    role: a.config.role as AgentConfig['role'],
    systemPrompt: a.config.system_prompt,
    color: a.config.color,
    status: a.status as AgentStatus,
    messageCount: a.message_count,
    unreadCount: a.unread_count,
  }))
}

// ─── Message routing ───────────────────────────────────────────────────────────

interface RawMessage {
  id: string
  from_agent: string
  to_agent: string
  content: string
  message_type: string
  timestamp: number
  round: number
}

function toMessage(m: RawMessage): Message {
  return {
    id: m.id,
    fromAgent: m.from_agent,
    toAgent: m.to_agent,
    content: m.content,
    type: m.message_type as Message['type'],
    timestamp: m.timestamp,
    round: m.round,
  }
}

export function routeMessage(msg: Omit<Message, 'id'>): string {
  return wasm().route_message(
    JSON.stringify({
      id: '',
      from_agent: msg.fromAgent,
      to_agent: msg.toAgent,
      content: msg.content,
      message_type: msg.type,
      timestamp: msg.timestamp,
      round: msg.round,
    }),
  )
}

export function getMessagesFor(agentId: string): Message[] {
  const raw: RawMessage[] = JSON.parse(wasm().get_messages_for(agentId))
  return raw.map(toMessage)
}

export function getMessageCountFor(agentId: string): number {
  return wasm().get_message_count_for(agentId)
}

export function getAllMessages(): Message[] {
  const raw: RawMessage[] = JSON.parse(wasm().get_all_messages_json())
  return raw.map(toMessage)
}

// ─── Status ────────────────────────────────────────────────────────────────────

export function updateAgentStatus(agentId: string, status: AgentStatus): void {
  wasm().update_agent_status(agentId, status)
}

export function getAgentStatus(agentId: string): AgentStatus {
  return wasm().get_agent_status(agentId) as AgentStatus
}

export function clearSession(): void {
  wasm().clear_session()
}

export function setRunning(running: boolean): void {
  wasm().set_running(running)
}
