/**
 * Reads the wasm-pack output .wasm file, base64-encodes it, and writes a TypeScript
 * module so Vite can inline it. This lets the final build be a single HTML file
 * with no external binary fetching.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const wasmPath = resolve(__dir, '../src/wasm/gremlin_coordinator_bg.wasm')
const outPath  = resolve(__dir, '../src/wasm/wasm_data.ts')

if (!existsSync(wasmPath)) {
  console.error(`[encode-wasm] ERROR: ${wasmPath} not found.`)
  console.error('  Run: wasm-pack build crates/coordinator --target web --out-dir web/src/wasm')
  process.exit(1)
}

const bytes  = readFileSync(wasmPath)
const base64 = bytes.toString('base64')
const kb     = (bytes.length / 1024).toFixed(1)

writeFileSync(
  outPath,
  `// Auto-generated by scripts/encode-wasm.mjs — do not edit manually.
// WASM binary: ${kb} KB (base64-encoded for single-file embedding)
export const WASM_BASE64 = "${base64}"
`,
)

console.log(`[encode-wasm] Encoded ${kb} KB → src/wasm/wasm_data.ts`)
