<script lang="ts">
  import type { AgentConfig, Message } from '../lib/types'
  import { cleanContent } from '../lib/cleanContent'
  import { enhanceProse } from '../lib/tableCards'
  import { sanitizeHtml } from '../lib/sanitize'
  import { marked } from 'marked'
  import { tick } from 'svelte'

  interface Props {
    messages: Message[]
    agents: AgentConfig[]
    logs: string[]
    streamingAgentId?: string | null
    streamingText?: string
    outputHtml?: string
    reportHtml?: string
    execSummaryHtml?: string
    isRunning?: boolean
    task?: string
    modeDescription?: string
    agentDescriptions?: Record<string, string>
    onCopy?: () => void
    onReply?: (text: string) => void
    onRetry?: (agentId: string) => void
  }
  const { messages, agents, logs, streamingAgentId = null, streamingText = '', outputHtml = '', reportHtml = '', execSummaryHtml = '', isRunning = false, task = '', modeDescription = '', agentDescriptions = {}, onCopy, onReply, onRetry }: Props = $props()

  let replyText = $state('')

  function sendReply() {
    const text = replyText.trim()
    if (!text || !onReply) return
    replyText = ''
    onReply(text)
  }

  // Messages always expand fully — no truncation

  let scrollEl = $state<HTMLDivElement | undefined>(undefined)
  let logEl = $state<HTMLDivElement | undefined>(undefined)

  const agentMap = $derived(new Map(agents.map((a) => [a.id, a])))

  function agentColor(id: string): string {
    return agentMap.get(id)?.color ?? 'var(--color-text-3)'
  }

  /** Extract the first sentence of a system prompt as a brief agent description. */
  /** Extract the first 2-3 sentences of a system prompt as a description. */
  function agentBrief(prompt: string): string {
    // Strip "You are a/an ..." preamble that most prompts start with
    const cleaned = prompt.replace(/^You are (?:a |an )?/i, '').trim()
    // Take up to 3 sentences or 300 chars
    const sentences = cleaned.match(/[^.!?\n]+[.!?]?/g) ?? [cleaned.slice(0, 300)]
    const brief = sentences.slice(0, 3).join('').trim()
    const capped = brief.length > 300 ? brief.slice(0, 297) + '…' : brief
    return capped.charAt(0).toUpperCase() + capped.slice(1)
  }

  /** Count messages sent by a specific agent. */
  function agentMessageCount(agentId: string): number {
    return messages.filter(m => m.fromAgent === agentId && m.type !== 'system').length
  }

  /** Count messages received by a specific agent. */
  function agentReceivedCount(agentId: string): number {
    return messages.filter(m => m.toAgent === agentId && m.type !== 'system').length
  }

  /** Role label for the agent summary. */
  function roleLabel(role: string): string {
    if (role === 'orchestrator') return 'Orchestrator'
    if (role === 'synthesizer') return 'Synthesizer'
    if (role === 'worker') return 'Analyst'
    return 'Agent'
  }

  function agentName(id: string): string {
    if (id === 'user') return 'USER'
    if (id === 'system') return 'SYSTEM'
    if (id === 'broadcast') return 'BROADCAST'
    return (agentMap.get(id)?.name ?? id).toUpperCase()
  }

  function formatTime(ts: number): string {
    const d = new Date(ts)
    return d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })
  }

  // Auto-scroll to bottom when new messages arrive or streaming text updates
  $effect(() => {
    void messages.length
    void streamingText
    tick().then(() => {
      if (scrollEl) scrollEl.scrollTop = scrollEl.scrollHeight
    })
  })

  // Auto-scroll log section independently
  $effect(() => {
    void logs.length
    tick().then(() => {
      if (logEl) logEl.scrollTop = logEl.scrollHeight
    })
  })
</script>

<div class="print-cover">
  <div class="cover-inner">
    <div class="cover-brand">⚡ GREMLIN</div>
    <div class="cover-rule"></div>
    {#if task}<div class="cover-task">{task}</div>{/if}
    {#if modeDescription}<div class="cover-mode">{modeDescription}</div>{/if}
    <div class="cover-meta">
      <div>{new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div>{messages.length} events · {agents.filter(a => a.role === 'worker' || a.role === 'custom').length} analysts</div>
    </div>
    <div class="cover-footer">Multi-agent intelligence report · Generated by Gremlin</div>
  </div>
</div>

<div class="print-agents">
  <div class="agents-header">Team Composition</div>
  <div class="agents-rule"></div>
  <div class="agents-list">
    {#each agents as agent}
      <div class="agent-entry">
        <div class="agent-entry-header">
          <span class="agent-entry-name" style="color: {agent.color}">{agent.name}</span>
          <span class="agent-entry-role">{roleLabel(agent.role)}</span>
        </div>
        <div class="agent-entry-brief">{agentDescriptions[agent.id] || agentBrief(agent.systemPrompt)}</div>
        <div class="agent-entry-meta">
          {#if agent.model}<span class="agent-entry-tag">{agent.model}</span>{/if}
          {#if agent.searchProvider}<span class="agent-entry-tag">search: {agent.searchProvider}</span>{/if}
          <span class="agent-entry-tag">{agentMessageCount(agent.id)} sent · {agentReceivedCount(agent.id)} received</span>
        </div>
      </div>
    {/each}
  </div>
</div>

{#if execSummaryHtml}
<div class="print-exec-summary">
  <div class="exec-header">Executive Summary</div>
  <div class="exec-rule"></div>
  <div class="exec-body prose-sm">{@html sanitizeHtml(execSummaryHtml)}</div>
</div>
{/if}

{#if reportHtml}
<div class="print-report">
  <div class="report-header">Full Report</div>
  <div class="report-rule"></div>
  <div class="report-body prose-sm">{@html sanitizeHtml(reportHtml)}</div>
</div>
{/if}

<div class="monitor" class:has-report={!!reportHtml}>
  <div class="monitor-header">
    <span class="label">Activity Monitor</span>
    <span class="count muted">{messages.length} events</span>
  </div>

  <div class="feed" bind:this={scrollEl} role="log" aria-live="polite" aria-label="Agent activity feed">
    {#if messages.length === 0 && logs.length === 0}
      <div class="empty">
        <div class="empty-icon">◉</div>
        <div>Awaiting session start…</div>
        <div class="empty-hint muted">Enter a task and press Run</div>
      </div>
    {/if}

    {#each messages as msg (msg.id)}
      <div class="event {msg.type}">
        <span class="time mono">{formatTime(msg.timestamp)}</span>
        <span class="route">
          <span class="agent-name" style="color: {agentColor(msg.fromAgent)}">{agentName(msg.fromAgent)}</span>
          <span class="arrow">→</span>
          <span class="agent-name" style="color: {agentColor(msg.toAgent)}">{agentName(msg.toAgent)}</span>
        </span>
        <span class="badge {msg.type === 'task' ? 'badge-warn' : msg.type === 'error' ? 'badge-error' : msg.type === 'human' ? 'badge-info' : msg.type === 'result' ? 'badge-accent' : 'badge-default'}">{msg.type}</span>
        {#if msg.type === 'error' && onRetry && isRunning}
          <button class="btn-retry" onclick={() => onRetry(msg.fromAgent)} aria-label="Retry {agentName(msg.fromAgent)}">Retry</button>
        {/if}
        <div class="content prose-sm">{@html sanitizeHtml(enhanceProse(marked.parse(cleanContent(msg.content)) as string))}</div>
      </div>
    {/each}

    {#if streamingAgentId && streamingText}
      {@const displayText = streamingText.replace(/<think>[\s\S]*?(<\/think>|$)/gi, '').trim()}
      <div class="event streaming">
        <span class="route">
          <span class="agent-name" style="color: {agentColor(streamingAgentId)}">{agentName(streamingAgentId)}</span>
          <span class="streaming-badge">streaming</span>
        </span>
        {#if displayText}
          <div class="content prose-sm streaming-content">{displayText}</div>
        {:else}
          <span class="typing-indicator">
            <span class="typing-dot"></span>
            <span class="typing-dot"></span>
            <span class="typing-dot"></span>
          </span>
        {/if}
      </div>
    {/if}

    {#if outputHtml && !isRunning}
      <div class="final-result">
        <div class="final-result-header">
          <span class="result-dot"></span>
          <span class="result-label">Result</span>
          {#if onCopy}
            <button class="ghost btn-sm" onclick={onCopy}>Copy</button>
          {/if}
        </div>
        <div class="result-body prose-sm">{@html sanitizeHtml(outputHtml)}</div>
        {#if onReply}
          <div class="reply-bar">
            <input
              class="reply-input"
              type="text"
              placeholder="Ask a follow-up…"
              bind:value={replyText}
              onkeydown={(e) => e.key === 'Enter' && sendReply()}
            />
            <button
              class="primary reply-btn"
              onclick={sendReply}
              disabled={!replyText.trim()}
            >Reply</button>
          </div>
        {/if}
      </div>
    {/if}
  </div>

  {#if logs.length > 0}
    <div class="log-section" bind:this={logEl}>
      {#each logs as log}
        <div class="log-line mono">{log}</div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .monitor {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
    border: 1px solid var(--glass-border);
    border-radius: var(--radius);
    background: var(--color-surface);
  }

  .monitor-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 14px;
    border-bottom: 1px solid var(--glass-border);
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
  }
  .label { color: var(--color-accent); }
  .count { font-family: var(--font-mono); }

  .feed {
    flex: 1;
    overflow-y: auto;
    padding: 8px 0;
    display: flex;
    flex-direction: column;
    gap: 1px;
  }

  .empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--color-text-4);
    gap: 8px;
    font-size: 13px;
  }
  .empty-icon { font-size: 28px; opacity: 0.4; }
  .empty-hint { font-size: 12px; margin-top: 4px; }

  .event {
    padding: 8px 14px;
    border-bottom: 1px solid rgba(48,54,61,0.5);
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    gap: 6px;
    font-size: 12px;
  }
  .event:last-child { border-bottom: none; }
  .event:hover { background: var(--surface-2); }

  .event.task    { border-left: 3px solid var(--color-accent-warn); padding-left: 11px; }
  .event.error   { border-left: 3px solid var(--color-accent-err);  padding-left: 11px; background: rgba(248,81,73,0.04); }
  .event.human   { border-left: 3px solid #58a6ff;           padding-left: 11px; background: rgba(88,166,255,0.04); }
  .event.system  { border-left: 3px solid var(--color-text-4);   padding-left: 11px; }
  .event.result  { border-left: 3px solid var(--color-accent);     padding-left: 11px; }

  .time {
    color: var(--color-text-4);
    font-size: 11px;
    flex-shrink: 0;
  }

  .route {
    display: flex;
    align-items: center;
    gap: 5px;
    flex-shrink: 0;
  }
  .agent-name {
    font-family: var(--font-mono);
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.02em;
  }
  .arrow { color: var(--color-text-4); }

  .content {
    width: 100%;
    color: var(--color-text);
    font-size: 12.5px;
    line-height: 1.5;
    word-break: break-word;
    padding-top: 3px;
  }

  /* ── Final result block ──────────────────────────────────────────── */
  .final-result {
    margin: 8px 10px 12px;
    border: 1px solid rgba(63,185,80,0.25);
    border-radius: 8px;
    background: rgba(63,185,80,0.03);
    animation: result-in 0.3s ease-out;
  }
  @keyframes result-in {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  .final-result-header {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 14px;
    border-bottom: 1px solid rgba(63,185,80,0.15);
  }
  .result-dot {
    width: 7px; height: 7px;
    border-radius: 50%;
    background: var(--color-accent);
    box-shadow: 0 0 8px rgba(63,185,80,0.6);
    flex-shrink: 0;
  }
  .result-label {
    font-size: 11px;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.07em;
    color: var(--color-accent);
    flex: 1;
  }
  .result-body {
    padding: 14px 16px;
    font-size: 13px;
    line-height: 1.65;
  }
  .reply-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 14px 10px;
    border-top: 1px solid rgba(63,185,80,0.12);
  }
  .reply-input {
    flex: 1;
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(48,54,61,0.5);
    border-radius: 5px;
    color: var(--color-text);
    font-size: 12px;
    padding: 6px 10px;
    outline: none;
    transition: all 0.15s ease;
  }
  .reply-input:focus {
    background: rgba(63,185,80,0.04);
    border-color: rgba(63,185,80,0.3);
    box-shadow: 0 0 0 2px rgba(63,185,80,0.08);
  }
  .reply-btn {
    flex-shrink: 0;
  }
  .btn-sm { font-size: 11px; }

  .log-section {
    padding: 8px 14px;
    border-top: 1px solid var(--glass-border);
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex-shrink: 0;
    max-height: 120px;
    overflow-y: auto;
  }
  .log-line {
    font-size: 11px;
    color: var(--color-text-4);
  }

  /* ── Typing indicator ──────────────────────────────────────────────── */
  .event.streaming {
    border-left: 3px solid var(--color-accent);
    padding-left: 11px;
    background: rgba(63,185,80,0.03);
    align-items: center;
  }

  .typing-label {
    font-size: 11px;
    font-style: italic;
  }

  .typing-indicator {
    display: inline-flex;
    align-items: center;
    gap: 3px;
    margin-left: 6px;
    vertical-align: middle;
  }

  .typing-dot {
    display: inline-block;
    width: 4px;
    height: 4px;
    border-radius: 50%;
    background: var(--color-accent);
    animation: typing-bounce 1.2s ease-in-out infinite;
  }
  .typing-dot:nth-child(2) { animation-delay: 0.2s; }
  .typing-dot:nth-child(3) { animation-delay: 0.4s; }

  @keyframes typing-bounce {
    0%, 60%, 100% { opacity: 0.3; transform: translateY(0); }
    30% { opacity: 1; transform: translateY(-3px); }
  }

  .streaming-badge {
    display: inline-block;
    font-size: 9px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-accent);
    background: rgba(63,185,80,0.1);
    border: 1px solid rgba(63,185,80,0.25);
    border-radius: 3px;
    padding: 1px 5px;
    margin-left: 6px;
    animation: pulse-badge 2s ease-in-out infinite;
  }

  @keyframes pulse-badge {
    0%, 100% { opacity: 0.7; }
    50% { opacity: 1; }
  }

  .streaming-content {
    white-space: pre-wrap;
    opacity: 0.5;
    font-family: var(--font-mono);
    font-size: 11px;
  }

  /* ── Print-only pages ──────────────────────────────────────── */
  .print-cover, .print-agents, .print-exec-summary, .print-report {
    display: none;
  }

  @media print {
    .monitor-header, .log-section, .reply-bar, .streaming-badge, .btn-retry { display: none !important; }

    /* When a polished report exists, hide the raw event feed entirely */
    .monitor.has-report { display: none !important; }

    /* Fallback: if no report, show the raw feed */
    .monitor:not(.has-report) { height: auto !important; overflow: visible !important; border: none !important; background: var(--color-bg) !important; }
    .monitor:not(.has-report) .feed { height: auto !important; overflow: visible !important; max-height: none !important; padding: 28px 32px !important; }

    /* ── Executive summary (1 page) ──────────────────────────────── */
    .print-exec-summary {
      display: block;
      padding: 48px 48px 32px;
      background: var(--color-bg);
      break-after: page;
    }
    .exec-header {
      font-family: var(--font-mono);
      font-size: 20px;
      font-weight: 700;
      color: var(--color-text);
      letter-spacing: 0.04em;
    }
    .exec-rule {
      width: 40px;
      height: 2px;
      background: var(--color-accent);
      margin: 12px 0 24px;
      opacity: 0.6;
    }
    .exec-body {
      font-size: 14px;
      line-height: 1.8;
      color: var(--color-text);
    }

    /* ── Full report ─────────────────────────────────────────────── */
    .print-report {
      display: block;
      padding: 48px 48px 32px;
      background: var(--color-bg);
    }
    .report-header {
      font-family: var(--font-mono);
      font-size: 20px;
      font-weight: 700;
      color: var(--color-text);
      letter-spacing: 0.04em;
    }
    .report-rule {
      width: 40px;
      height: 2px;
      background: var(--color-accent);
      margin: 12px 0 24px;
      opacity: 0.6;
    }
    .report-body {
      font-size: 13px;
      line-height: 1.7;
      color: var(--color-text);
    }

    /* ── Cover page ──────────────────────────────────────────────── */
    .print-cover {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      background: var(--color-bg);
    }
    .cover-inner {
      text-align: center;
      max-width: 500px;
    }
    .cover-brand {
      font-family: var(--font-mono);
      font-size: 42px;
      font-weight: 800;
      letter-spacing: 0.14em;
      color: var(--color-accent);
    }
    .cover-rule {
      width: 60px;
      height: 2px;
      background: var(--color-accent);
      margin: 20px auto;
      opacity: 0.6;
    }
    .cover-task {
      font-size: 20px;
      color: var(--color-text);
      margin-top: 24px;
      line-height: 1.5;
      font-weight: 500;
    }
    .cover-mode {
      font-size: 12px;
      color: var(--color-text-3);
      margin-top: 12px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }
    .cover-meta {
      font-size: 12px;
      color: var(--color-text-4);
      margin-top: 40px;
      font-family: var(--font-mono);
      line-height: 1.8;
    }
    .cover-footer {
      font-size: 10px;
      color: var(--color-text-4);
      margin-top: 60px;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      opacity: 0.5;
    }

    /* ── Agent summary page (page 2) ─────────────────────────────── */
    .print-agents {
      display: block;
      padding: 48px 48px 32px;
      background: var(--color-bg);
    }
    .agents-header {
      font-family: var(--font-mono);
      font-size: 20px;
      font-weight: 700;
      color: var(--color-text);
      letter-spacing: 0.04em;
    }
    .agents-rule {
      width: 40px;
      height: 2px;
      background: var(--color-accent);
      margin: 12px 0 20px;
      opacity: 0.6;
    }
    .agents-list {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }
    .agent-entry {
      padding: 8px 12px;
      border-left: 3px solid var(--color-border);
      background: rgba(255,255,255,0.02);
      page-break-inside: avoid;
    }
    .agent-entry-header {
      display: flex;
      align-items: baseline;
      gap: 8px;
    }
    .agent-entry-name {
      font-weight: 600;
      font-size: 13px;
    }
    .agent-entry-role {
      font-family: var(--font-mono);
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--color-text-4);
    }
    .agent-entry-brief {
      font-size: 11px;
      color: var(--color-text-3);
      margin-top: 3px;
      line-height: 1.45;
    }
    .agent-entry-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
      margin-top: 4px;
    }
    .agent-entry-tag {
      font-family: var(--font-mono);
      font-size: 9px;
      color: var(--color-text-4);
      background: rgba(255,255,255,0.04);
      border: 1px solid rgba(255,255,255,0.06);
      border-radius: 3px;
      padding: 1px 5px;
    }

    /* ── Formal event styling ────────────────────────────────────── */
    .event {
      padding: 12px 16px !important;
      margin-bottom: 4px;
      border-radius: 4px;
    }
    .event.system {
      opacity: 0.7;
      font-size: 11px;
    }
    .content {
      font-size: 13px !important;
      line-height: 1.65 !important;
    }

    /* ── Page footer with branding ───────────────────────────────── */
    @page {
      margin: 0;
      @bottom-center {
        content: "⚡ GREMLIN";
        font-size: 8px;
        color: #666;
      }
    }
  }

</style>
